name: "scala CI workflow ubuntu"

on:
  push:
    # branches: [ $default-branch ]
    branches: [ dev ]
  # pull_request:
  #   branches: [ $default-branch ]

jobs:
  
# https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-java-with-ant
  build-linux-job:
    name: "Specifying the JVM version and architecture on ubuntu-18.04"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "Set up JDK 9.0.4 for x64"
      uses: actions/setup-java@v1
      with:
          java-version: '9.0.4'
          architecture: x64        
    - name: Run tests
      run: sbt test

  build-linux-scala-job:
    name: "Specifying the JVM version  ubuntu-18.04"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run tests
      run: sbt test

